## NOTES

1.NumPY:使用python進行線性代數運算的模組
(線性代數、矩陣)

2.NumPY:沒有index & lebal

3.NumPY:可以是多維陣列

4.row/column



1.Series
(1)index：索引鍵(類似ID)
(2)values：值

透過這兩個屬性可以取到Series裡的資料


In [ ]:
## CODE

In [3]:
import numpy as np

np.array([[1,2,3],[4,5,6],[7,8,9]]) #，區隔即是一個 row


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.ones((4,5)) #row:4個 1 ； column:5個 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
data

print(data[0]) #print出來是第1個 row
print(data[1,3])#print出來是第2個 row，第4個column

[1 2 3 4]
8


## Exercise

In [ ]:
利用下面的資料建立DataFrame 
list1 = [[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]] 
columns = ['Math', 'English', 'History'] 
index=['Simon','Allen','Jimmy','Peter']

In [129]:
import pandas as pd

df = pd.DataFrame([[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]] ,index=['Simon','Allen','Jimmy','Peter'],
                 columns=['Math', 'English', 'History'])
df

Math  English  History
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60

取出數學>60 且英文>85 的資料, 並以DataFrame的方式呈現

In [130]:
df[df['Math']>60]
df[df['English']>85]


Math  English  History
Jimmy    70       90       88

計算各科的平均數

In [131]:
df1 = pd.DataFrame([df['Math'].mean(),df['English'].mean(),df['History'].mean()] ,
                  index=['Math', 'English', 'History'],
                 columns=['各科平均分數'])
df1

各科平均分數
Math       72.5
English    67.5
History    64.0

依各科分數來個別排名

In [132]:
print(df['Math'].rank(ascending=False))
print()
print(df['English'].rank(ascending=False))
print()
print(df['History'].rank(ascending=False))

Simon    1.0
Allen    4.0
Jimmy    3.0
Peter    2.0
Name: Math, dtype: float64

Simon    3.0
Allen    2.0
Jimmy    1.0
Peter    4.0
Name: English, dtype: float64

Simon    4.0
Allen    2.0
Jimmy    1.0
Peter    3.0
Name: History, dtype: float64


新增性別資料
Gender = ['M'.'F','M','M']

In [133]:
df['Gender'] = ['M','F','M','M']
df

Math  English  History Gender
Simon    90       60       33      M
Allen    50       70       75      F
Jimmy    70       90       88      M
Peter    80       50       60      M

性別的類別各出現幾次？

In [137]:
df['Gender'].value_counts()

M    3
F    1
Name: Gender, dtype: int64

算出每位同學的平均分數，再用平均分數排名

In [118]:
df2 = df.mean(axis=1)
print(df2)

df2.rank(ascending=False)

Simon    61.000000
Allen    65.000000
Jimmy    82.666667
Peter    63.333333
dtype: float64


Simon    4.0
Allen    2.0
Jimmy    1.0
Peter    3.0
dtype: float64